// Shared HTTP status mapping for Billing Operations controllers -- same
// "known business error codes map to a specific status, everything else is
// a logged 500" shape as billing-provisioning.controller.js.
const STATUS_BY_CODE = {
  STATEMENT_NOT_FOUND: 404,
  ATTEMPT_NOT_FOUND: 404,
  BILLING_PERIOD_NOT_FOUND: 404,
  ENTITY_NOT_FOUND: 404,

  MISSING_PERIOD_BOUNDS: 400,
  MISSING_BANK_DETAILS: 400,
  MISSING_STATEMENT_IDS: 400,
  INVALID_OUTCOME: 400,
  MISSING_PROVIDER_REFERENCE: 400,

  PERIOD_OVERLAP: 409,
  NOT_PRODUCTION_RUN: 409,
  NO_COMPONENTS: 409,
  DONATION_NOT_PAID: 409,
  DONATION_IS_MOCK: 409,
  AMOUNT_DRIFT: 409,
  ENTITY_MISMATCH: 409,
  DONATION_ALREADY_CLAIMED_BY_OTHER_STATEMENT: 409,
  APPROVAL_INTEGRITY_VIOLATION: 409,
  CANNOT_APPROVE_ABANDONED: 409,
  CANNOT_ABANDON_EFFECTIVE_STATEMENT: 409,
  MASAV_NOT_CONFIGURED: 409,
  MASAV_INCOMPLETE: 409,
  NOT_A_MASAV_ATTEMPT: 409,
  ATTEMPT_NOT_ACTIVE: 409,
  NOT_AUTHORIZED: 409,
  NO_OPEN_ATTEMPT: 409,
  NOT_COLLECTION_READY: 409,
};

function statusFor(err) {
  return STATUS_BY_CODE[err.code] || 500;
}

module.exports = { statusFor };
