ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS show_logo          BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_hero_title    BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_hero_subtitle BOOLEAN NOT NULL DEFAULT true;
