ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_locked   BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS deleted_at  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deleted_by  BIGINT REFERENCES users(id);

ALTER TABLE platform_audit_log
  ADD COLUMN IF NOT EXISTS campaign_id UUID REFERENCES campaigns(id);
